name: create teams
on: [workflow_dispatch]
jobs: 
   create_team:
     runs-on: ubuntu-latest
     steps:
        - run: gh api --method POST  -H "Accept: application/vnd.github+json"  -H "X-GitHub-Api-Version: 2022-11-28" \
                /orgs/jp-apptesting/teams   -f name='Junk League'  -f description='A Junk team'  -f permission='push' \
                -f notification_setting='notifications_enabled'  -f privacy='closed
     env:
       GITHUB_TOKEN: ${{ secrets.JP_TOKEN }}
       OWNER: ${{ github.repository_owner }}
