name: create teams
on: [workflow_dispatch]
env: 
  ACCEPT_STR: "Accept: application/vnd.github+json"
  API_VER: "X-GitHub-Api-Version: 2022-11-28"

jobs:
    runs-on: ubuntu-latest
    steps:
      - name: Generate a token
        id: generate_token
        uses: actions/create-github-app-token@v1
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}
      - name: Create Team
        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
          OWNER: ${{ github.repository_owner }}
        run: |
          gh api --method POST  -H "$ACCEPT_STR"  -H "$API_VER"  /orgs/jp-apptesting/teams  -f name='Junk League'  -f description='A Junk team'  -f permission='push'  -f notification_setting='notifications_enabled'  -f privacy='closed'
