name: create teams
on: [workflow_dispatch]
env: 
  ACCEPT_STR: "Accept: application/vnd.github+json"
  API_VER: "X-GitHub-Api-Version: 2022-11-28"
  END_POINT: "/orgs/jp-apptesting/teams"
  TEAM_NAME: "Men in Blue"
jobs:
  jp_testapp:
    runs-on: ubuntu-latest
    steps:
      - name: Generate a token
        id: generate_token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
      - name: Create Team
        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
          OWNER: ${{ github.repository_owner }}
        run: |
          gh api --method POST  -H "$ACCEPT_STR"  -H "$API_VER"  $END_POINT  -f name='Men in blue'  -f description='A Blue team'  -f permission='push'  -f notification_setting='notifications_enabled'  -f privacy='closed'
